authapp/urls.py
from django.urls import path
import authapp.views as authapp_views

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp_views.login, name='login'),
    path('logout/', authapp_views.logout, name='logout'),
    path('register/', authapp_views.register, name='register'),
    path('profile/<int:pk>/', authapp_views.UserProfile.as_view(), name='profile'),
    path('all/', authapp_views.UserAll.as_view(), name='all_user'),
    path('active/<int:pk>/', authapp_views.UserActive.as_view(), name='active_user'),
    path('remove/<int:pk>/', authapp_views.UserRemove.as_view(), name='remove_user'),
    path('edit/<int:pk>/', authapp_views.UserUpdate.as_view(), name='edit_user'),
]

edo/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from libapp import views as libapp_views
from django.conf.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('lib/', include('libapp.urls', namespace='library')),
    path('blog/', include('blogapp.urls', namespace='blog')),
    path('doc/', include('docapp.urls', namespace='docapp')),
    path('', libapp_views.main, name='index'),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

libapp/urls.py
from django.urls import path
import libapp.views as libapp_views

app_name = 'libapp'

urlpatterns = [
    path('lib/', libapp_views.libs, name='library'),

]

libapp/models.py
from django.core.exceptions import ValidationError
from django.db import models
from django.contrib.auth.hashers import make_password


# Create your models here.


class AccessLevel(models.Model):
    level = models.PositiveIntegerField(verbose_name='Уровень доступа', default=0)
    description = models.TextField(verbose_name='Описание категории', blank=True)

    def __str__(self):
        return self.description


class Category(models.Model):
    """Класс Category является родительским классом для таких классов как MainMenu,

            Основное применение - задает общие характеристики дочерним классам

            Attributes
            ----------
            parent_category : ForeignKey
                внешний ключ на себя, служит для организации подкатегорий объекта
            name : str
                содержит название категории
            description : str
                содержит описание категории
            access : ForeignKey
                внешний ключ на модель AccessLevel, служит для определения категории доступа

            Methods
            -------
            __str__(self)
                используется для представления отдельных записей на сайте администрирования
                (и в любом другом месте, где нужно обратиться к экземпляру модели).
        """

    class Meta:
        abstract = True

    parent_category = models.ForeignKey('self', on_delete=models.CASCADE, null=True, blank=True)
    name = models.CharField(verbose_name='Название категории', max_length=128, unique=True)
    description = models.TextField(verbose_name='Описание категории', blank=True)
    access = models.ForeignKey(AccessLevel, default=0, on_delete=models.SET_DEFAULT, verbose_name='Категория доступа')
    hash_view = models.CharField(max_length=256, blank=True)

    def __str__(self):
        if self.parent_category:
            return f'{self.parent_category}/{self.name}'
        else:
            return self.name

    def save(self, **kwargs):
        some_salt = 'some_salt'
        self.hash_view = make_password(self.name, some_salt)
        super().save(**kwargs)


class MainMenu(Category):
    sequence_number = models.PositiveIntegerField(verbose_name='порядковый номер', default=0)
    url_address = models.CharField(verbose_name='ссылка на страницу', max_length=128, default='index', null=False)

    def __init__(self, *args, **kwargs):
        super(MainMenu, self).__init__(*args, **kwargs)


class Division(Category):

    def __init__(self, *args, **kwargs):
        super(Division, self).__init__(*args, **kwargs)

libapp/views.py
from django.shortcuts import render
from libapp.models import MainMenu
from blogapp.models import Blog, BlogCategory
from authapp.models import Counteragent
from edo.utilities import main_menu_generate, footer_info_generator


def libs():
    pass


def main(request):
    blog_category = BlogCategory.objects.all().order_by('pk')
    blog_post = Blog.objects.all().order_by('time_publication')
    context = {
        'title': 'ООО Авиакомпания "БАРКОЛ" - БИБЛИОТЕКА',
        'blog_category': blog_category,
        'blog_post': blog_post,
    }
    context.update(main_menu_generate(MainMenu.objects.all()))
    try:
        context.update(footer_info_generator(Counteragent.objects.get(base_counteragent=True)))
    except Exception:
        pass
    return render(request, 'libapp/index.html', context)

libapp/templates/libapp/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% block heads %}
    {% endblock %}
    <!-- google fonts roboto regular -->
    <link rel='stylesheet' href='https://fonts.googleapis.com/css?family=Roboto:400,700,300,500' type='text/css'>
    <link rel='stylesheet' href='https://fonts.googleapis.com/css?family=Lora:400,700' type='text/css'>
    <link rel="stylesheet" href="{% static 'css/owl.carousel.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.theme.default.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/jquery-ui.css' %}">
    <link rel="stylesheet" href="{% static 'css/jquery-ui.structure.css' %}">
    <link rel="stylesheet" href="{% static 'css/jquery-ui.theme.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/jquery.timepicker.css' %}">
    <link rel="stylesheet" href="{% static 'css/jquery.countdown.css' %}">
    <link rel="stylesheet" href="{% static 'css/flexslider.css' %}">
    <link rel="stylesheet" href="{% static 'css/red.css' %}">
    <link rel="stylesheet" href="{% static 'css/select2.css' %}">
    <link rel="stylesheet" href="{% static 'css/plyr.css' %}">
    <link rel="stylesheet" href="{% static 'css/jquery.raty.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/hotel.style.css' %}">
</head>

<body class="rq-homepage-one">

<div id="rq-circle-loader-wrapper">
    <div id="rq-circle-loader-center">
        <div class="rq-circle-load">
            <img src="{% static 'img/oval.svg' %}" alt="Page Loader">
        </div>
    </div>
</div>

<!--================================
               MAIN BLOCK
    =================================-->
<div id="main-wrapper">

    <!--================================
                    SIDE MENU
        =================================-->
    {% include 'libapp/side_menu.html' %}

    <!--================================
              Navigation Menu start
        =================================-->
    {% include 'libapp/nav.html' %}

    <!--================================
              Block content start
        =================================-->
    {% block content %}
    {% endblock %}

    <!--================================
                     Footer
        =================================-->
    {% include 'libapp/footer.html' %}

</div>
<!--main-wrapper-->

<!-- Latest jQuery plugin-->
<script src="{% static 'js/main.js' %}"></script>
<!-- Latest compiled and minified JavaScript for bootstrap-->
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/owl.carousel.min.js' %}"></script>
<script src="{% static 'js/parallax.min.js' %}"></script>
<script src="{% static 'js/jquery-ui.min.js' %}"></script>
<script src="{% static 'js/jquery.timepicker.min.js' %}"></script>
<script src="{% static 'js/jquery.countdown.min.js' %}"></script>
<script src="{% static 'js/jquery.flexslider-min.js' %}"></script>
<script src="{% static 'js/select2.min.js' %}"></script>
<script src="{% static 'js/icheck.min.js' %}"></script>
<script src="{% static 'js/jquery.raty.js' %}"></script>
<script src="{% static 'js/jquery.datetimepicker.full.min.js' %}"></script>
<script src="{% static 'js/scripts.js' %}"></script>

</body>

</html>

libapp/templates/libapp/footer.html
{% load staticfiles %}

<!-- Footer -->
<footer class="footer">
    <div class="rq-footer-top">
        <div class="container">
            <div class="row">
                <div class="col-md-2 col-sm-6 col-xs-12">
                    <div class="footer-logo">
                        <img src="{% static 'img/footer-logo2.png' %}" class="img-responsive"
                             alt="Responsive image"/>
                    </div>
                </div>
                <div class="col-md-4 col-sm-6 col-xs-12">
                    <h5>наш адрес</h5>
                    <address>
                        <ul>
                            <li class="rq-hotel-address"><i class="fa fa-map-marker"></i>{{ address }}</li>
                            <li class="rq-phone"><i class="fa fa-phone"></i>{{ phone_number }}</li>
                            <li class="rq-email"><i class="fa fa-envelope-o"></i>{{ email }}</li>
                        </ul>
                    </address>
                </div>
                <div class="col-md-3 col-sm-6 col-xs-12">
                    <h5>полезные ссылки</h5>
                    <ul class="rq-footer-links">
                        <li><a href="https://favt.gov.ru/" target="_blank">ФЕДЕРАЛЬНОЕ АГЕНТСТВО ВОЗДУШНОГО
                            ТРАНСПОРТА</a></li>
                        <li><a href="https://mintrans.gov.ru/" target="_blank">МИНИСТЕРСТВО ТРАНСПОРТА РОССИЙСКОЙ
                            ФЕДЕРАЦИИ</a></li>
                        <li><a href="https://www.icao.int/" target="_blank">МЕЖДУНАРОДНАЯ ОРГАНИЗАЦИЯ ГРАЖДАНСКОЙ
                            АВИАЦИИ (ICAO)</a></li>
                        <li><a href="https://www.gosuslugi.ru/" target="_blank">ПОРТАЛ ГОСУДАРСТВЕННЫХ УСЛУГ РОССИЙСКОЙ
                            ФЕДЕРАЦИИ</a></li>
                        <li><a href="http://www.pfrf.ru/" target="_blank">ПЕНСИОННЫЙ ФОНД РОССИЙСКОЙ ФЕДЕРАЦИИ</a></li>
                    </ul>
                </div>
                <div class="col-md-3 col-sm-6 col-xs-12">
                    <h5>новостная рассылка</h5>
                    <input type="email" class="form-control" id="exampleInputEmail1" placeholder="Email">
                    <div class="rq-common-btn">
                        <button class="btn rq-btn-primary" type="submit">отправить</button>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="rq-footer-bottom">
        <div class="container">
            <div class="row">
                <p>&copy; Авторское право {% now 'Y' %}. Все права защищены</p>
            </div>
        </div>
    </div>
</footer>

libapp/templates/libapp/index.html
{% extends 'libapp/base.html' %}
{% load staticfiles %}

{% block heads %}
    <title>{{ title }}</title>
{% endblock %}

{% block content %}
    <section class="rq-page-background rq-blog-page-bg">
        <div class="banner_shadow">
            <h1>{{ title }}</h1>
        </div>
    </section>


{% endblock %}

libapp/templates/libapp/nav.html
{% load staticfiles %}
{% load utilities %}
<header>
    <!-- Navigation Menu start-->
    <nav class="navbar rq-header-main-menu navbar-fixed-top" role="navigation">
        <div class="container-fluid">
            <!-- Navbar Toggle -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                        data-target=".navbar-collapse" aria-expanded="false">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>

                <!-- Logo -->
                <a class="navbar-brand" href="{% url 'index' %}"><img class="logo" src="{% static 'img/logo2.png' %}"
                                                                      alt="Houston"></a>
            </div>
            <!-- Navbar Toggle End -->

            <!-- navbar-collapse start-->
            <div id="nav-menu" class="navbar-collapse rq-menu-wrapper collapse" role="navigation">
                <ul class="nav navbar-nav rq-menus">
                    {% for key, value in nav_hash.items %}
                        <li class="active">
                            <a href="{% url value.1 %}">{{ value.0 }}</a>
                            {% if value|len:'2' %}
                                <ul class="rq-sub-menu">
                                    {% for item in value|sls:'2' %}
                                        <li>
                                            <a href="{% if item.1 %} {% url item.1 %} {% else %}#{% endif %}">{{ item.0 }}</a>
                                        </li>
                                    {% endfor %}
                                </ul>
                            {% endif %}
                        </li>
                    {% endfor %}

                    {% if user.is_superuser or user.is_staff %}
                        <li>
                            <a href="{% url 'admin:index' %}">Admin</a>
                        </li>
                    {% endif %}
                </ul>
            </div>
            <!-- navbar-collapse end-->

            <div class="rq-extra-btns-wrapper">
                <div class="rq-language">
                    <select class="js-example-placeholder-single form-control">
                        <option value="Eng">EN</option>
                        <option value="Spn">SPN</option>
                        <option value="Ger">GER</option>
                        <option value="Rus">RUS</option>
                    </select>
                </div>
                <button id="rq-side-menu-btn" class="cd-btn btn rq-sidemenu-btn"></button>
            </div>

        </div>
    </nav>
    <!-- Navigation Menu end-->
</header> <!-- / rq-header-section end here-->

libapp/templates/libapp/side_menu.html
<!--================================
                SIDE MENU
    =================================-->
<!-- PAGE OVERLAY WHEN MENU ACTIVE -->
<div class="rq-side-menu-overlay"></div>
<!-- PAGE OVERLAY WHEN MENU ACTIVE END -->

<div class="rq-side-menu-wrap">
    <!-- OVERLAY -->
    <div class="rq-dark-overlay"></div>
    <!-- OVERLAY END -->

    <div id="rq-side-menu" class="rq-side-menu">
        <div class="rq-side-menu-widget-wrap">
            <div class="rq-login-form-wrapper">
                {% if not user.is_authenticated %}
                    <h3>Вход пользователя</h3>
                    <p>Войдите в систему, чтобы получить доступ ко всем функциям</p>

                    <div class="rq-login-form">
                        <form action="{% url 'authapp:login' %}" method="post">
                            {% csrf_token %}
                            <input type="text" name="username" id="rq-user-input" placeholder="User Name">
                            <input type="password" name="password" id="rq-user-password" placeholder="Password">
                            <button type="submit">Войти</button>
                        </form>
                    </div>

                    <div class="rq-social-login-opt">
                        <a href="#" class="rq-social-login-btn rq-facebook-login">Login with Facebook</a>
                        <a href="#" class="rq-social-login-btn rq-twitter-login">Login with Twitter</a>
                    </div>

                    <div class="rq-other-options">
                        <a href="#" class="rq-forgot-pass">Забыли пароль?</a>
                        <a href="{% url 'authapp:register' %}" class="rq-signup">Регистрация</a>
                    </div>
                {% else %}
                    <div class="rq-other-options">
                        <a href="{% url 'authapp:profile' user.pk %}" class="rq-forgot-pass">Мой профиль</a>
                        <a href="{% url 'authapp:logout' %}" class="rq-signup">Выход</a>
                    </div>
                {% endif %}
            </div>
        </div>
    </div>

    <button class="rq-side-menu-close-button" id="rq-side-menu-close-button">Close Menu</button>
</div>
<!-- SIDE MENU END -->