authapp/urls.py
from django.urls import path
import authapp.views as authapp_views

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp_views.login, name='login'),
    path('logout/', authapp_views.logout, name='logout'),
    path('register/', authapp_views.register, name='register'),
    path('profile/<int:pk>/', authapp_views.UserProfile.as_view(), name='profile'),
    path('all/', authapp_views.UserAll.as_view(), name='all_user'),
    path('active/<int:pk>/', authapp_views.UserActive.as_view(), name='active_user'),
    path('remove/<int:pk>/', authapp_views.UserRemove.as_view(), name='remove_user'),
    path('edit/<int:pk>/', authapp_views.UserUpdate.as_view(), name='edit_user'),
]

edo/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from libapp import views as libapp_views
from django.conf.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('lib/', include('libapp.urls', namespace='library')),
    path('blog/', include('blogapp.urls', namespace='blog')),
    path('doc/', include('docapp.urls', namespace='docapp')),
    path('', libapp_views.main, name='index'),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

libapp/urls.py
from django.urls import path
import libapp.views as libapp_views

app_name = 'libapp'

urlpatterns = [
    path('lib/', libapp_views.libs, name='library'),

]

authapp/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from libapp.models import Division, AccessLevel


class Country(models.Model):
    code = models.CharField(verbose_name='код', max_length=3, blank=True, null=True, help_text='')
    name = models.CharField(verbose_name='страна', max_length=30, blank=True, null=True, help_text='')

    def __str__(self):
        return self.name


class City(models.Model):
    city_id = models.IntegerField(verbose_name='')
    country = models.ForeignKey(Country, on_delete=models.SET_NULL, null=True, help_text='')
    city_name = models.CharField(verbose_name='город', max_length=30, blank=True, null=True, help_text='')

    def __str__(self):
        return self.city_name


class Weather(models.Model):
    weather_date = models.DateField(verbose_name='Дата')
    coord_lon = models.FloatField(verbose_name='Долгота')
    coord_lat = models.FloatField(verbose_name='Широта')
    weather_id = models.IntegerField(verbose_name='ID')
    weather_main = models.CharField(verbose_name='Погодные явление', max_length=20, blank=True, null=True, help_text='')
    weather_description = models.CharField(verbose_name='Погодные условия', max_length=40, blank=True, null=True,
                                           help_text='')
    weather_icon = models.CharField(verbose_name='Иконка', max_length=4, blank=True, null=True, help_text='')
    main_temp = models.FloatField(verbose_name='Температура')
    main_feels_like = models.FloatField(verbose_name='Ощущение')
    main_temp_min = models.FloatField(verbose_name='Минимальная температура')
    main_temp_max = models.FloatField(verbose_name='Максимальная температура')
    main_pressure = models.FloatField(verbose_name='Давление')
    main_humidity = models.IntegerField(verbose_name='Влажность')
    visibility = models.IntegerField(verbose_name='Видимость')
    wind_speed = models.IntegerField(verbose_name='Скорость ветра')
    wind_deg = models.IntegerField(verbose_name='Направление ветра')
    country = models.ForeignKey(Country, on_delete=models.SET_NULL, null=True, help_text='', verbose_name='Страна')
    city = models.ForeignKey(City, on_delete=models.SET_NULL, null=True, help_text='', verbose_name='Город')

    def __str__(self):
        return f'{self.city} / {self.weather_date}'


class PhoneNumber(models.Model):
    number = models.CharField(verbose_name='Номер телефона', max_length=15)

    def __str__(self):
        return f'{self.number}'


class Address(models.Model):
    postal_code = models.CharField(verbose_name='индекс', max_length=6, blank=True, null=True, help_text='')
    country = models.ForeignKey(Country, verbose_name='страна', on_delete=models.SET_NULL, null=True, help_text='')
    region = models.CharField(verbose_name='область', max_length=30, blank=True, null=True, help_text='')
    district = models.CharField(verbose_name='район', max_length=30, blank=True, null=True, help_text='')
    microdistrict = models.CharField(verbose_name='микрорайон', max_length=30, blank=True, null=True, help_text='')
    city = models.ForeignKey(City, verbose_name='город', on_delete=models.SET_NULL, null=True, help_text='')
    street = models.CharField(verbose_name='улица', max_length=60, blank=True, null=True, help_text='')
    house = models.CharField(verbose_name='дом', max_length=6, blank=True, null=True, help_text='')
    apartment = models.CharField(verbose_name='квартира', max_length=3, blank=True, null=True, help_text='')

    def __str__(self):
        result = ''
        if self.postal_code:
            result += f'{self.postal_code}'
        if self.country:
            result += f', {self.country}'
        if self.region:
            result += f', {self.region}'
        if self.city:
            result += f', г. {self.city}'
        if self.street:
            result += f', ул. {self.street}'
        if self.house:
            result += f', д. {self.house}'
        if self.apartment:
            result += f', кв. {self.apartment}'

        return result


class Job(models.Model):
    code = models.CharField(verbose_name='код должности', max_length=100, help_text='', default='000')
    name = models.CharField(verbose_name='должность', max_length=100, help_text='')

    def __str__(self):
        return f'{self.name}'


class Work(models.Model):
    job = models.ForeignKey(Job, verbose_name='должность', on_delete=models.SET_NULL, null=True, help_text='')
    divisions = models.ForeignKey(Division, verbose_name='подразделение', on_delete=models.SET_NULL, null=True,
                                  help_text='')

    def __str__(self):
        return f'{self.job} / {self.divisions}'


class Person(AbstractUser):
    type_of = [
        ('natural_person', 'физическое лицо'),
        ('staff_member', 'штатный сотрудник'),
        ('freelancer', 'внештатный сотрудник')
    ]
    type_of_gender = [
        ('male', 'мужской'),
        ('female', 'женский')
    ]
    surname = models.CharField(verbose_name='отчество', max_length=40, blank=True, null=True, help_text='')
    avatar = models.ImageField(upload_to='users_avatars', blank=True, help_text='')
    birthday = models.DateField(verbose_name='день рождения', blank=True, null=True, help_text='')
    access_right = models.ManyToManyField(AccessLevel, verbose_name='права доступа', default=0, help_text='')
    address = models.ForeignKey(Address, on_delete=models.SET_NULL, null=True, help_text='')
    type_users = models.CharField(verbose_name='тип пользователя', max_length=40, choices=type_of, help_text='')
    phone = models.OneToOneField(PhoneNumber, verbose_name='номер телефона', on_delete=models.SET_NULL, null=True,
                                 related_name='cell')
    corp_phone = models.OneToOneField(PhoneNumber, verbose_name='корпоративный номер', on_delete=models.SET_NULL,
                                      null=True, related_name='corp')
    works = models.ForeignKey(Work, verbose_name='занятость', on_delete=models.SET_NULL, blank=True, null=True)
    gender = models.CharField(verbose_name='пол', max_length=7, blank=True, choices=type_of_gender, help_text='')

    def __str__(self):
        return f'{self.last_name} {self.first_name} {self.surname}'


class Counteragent(models.Model):
    short_name = models.CharField(verbose_name='Наименование', max_length=150, default='', help_text='')
    full_name = models.CharField(verbose_name='Полное наименование', max_length=250, default='', help_text='')
    inn = models.CharField(verbose_name='ИНН', max_length=12, blank=True, null=True, help_text='')
    kpp = models.CharField(verbose_name='КПП', max_length=9, blank=True, null=True, help_text='')
    type_of = [
        ('juridical_person', 'юридическое лицо'),
        ('physical_person', 'физическое лицо'),
        ('separate_subdivision', 'обособленное подразделение'),
        ('government_agency', 'государственный орган'),
    ]
    type_counteragent = models.CharField(verbose_name='Тип контрагента', max_length=40, choices=type_of, help_text='')
    juridical_address = models.ForeignKey(Address, verbose_name='Юридический адрес', on_delete=models.SET_NULL,
                                          null=True, related_name='juridical')
    physical_address = models.ForeignKey(Address, verbose_name='Физический адрес', on_delete=models.SET_NULL, null=True,
                                         related_name='physical')
    email = models.EmailField(verbose_name='Email', null=True)
    phone = models.ForeignKey(PhoneNumber, verbose_name='Номер телефона', on_delete=models.SET_NULL, null=True)
    base_counteragent = models.BooleanField(verbose_name='Основная организация', default=False)
    director = models.ForeignKey(Person, verbose_name='Директор', on_delete=models.SET_NULL, null=True, blank=True,
                                 related_name='direct')
    accountant = models.ForeignKey(Person, verbose_name='Бухгалтер', on_delete=models.SET_NULL, null=True, blank=True,
                                   related_name='account')
    contact_person = models.ForeignKey(Person, verbose_name='Контактное лицо', on_delete=models.SET_NULL, null=True,
                                       blank=True, related_name='contact')

    def __str__(self):
        return f'{self.short_name}, {self.inn}/{self.kpp}'

authapp/forms.py
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UserChangeForm
from django import forms
from authapp.models import Person


class UserLoginForm(AuthenticationForm):
    class Meta:
        model = Person
        fields = ('username', 'password')

    def __init__(self, *args, **kwargs):
        super(UserLoginForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class UserEditForm(UserChangeForm):
    class Meta:
        model = Person
        fields = ('username', 'first_name', 'last_name', 'email', 'birthday', 'password', 'avatar')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control mb-4'
            field.help_text = ''
            if field_name == 'password':
                field.widget = forms.HiddenInput()


class UserUpdateForm(UserChangeForm):
    class Meta:
        model = Person
        fields = (
            'username', 'first_name', 'last_name', 'email', 'birthday', 'password', 'avatar', 'access_right', 'address',
            'type_users', 'phone', 'corp_phone', 'works', 'gender', 'surname')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control mb-4'
            field.help_text = ''
            if field_name == 'password':
                field.widget = forms.HiddenInput()


class UserRegisterForm(UserCreationForm):
    class Meta:
        model = Person
        fields = ('username', 'first_name', 'last_name', 'password1', 'password2', 'email')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['first_name'].required = True
        self.fields['last_name'].required = True
        self.fields['email'].required = True
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control mb-4'
            # field.help_text = ''


class UserProfileForm(UserChangeForm):
    class Meta:
        model = Person
        fields = (
            'username', 'first_name', 'last_name', 'surname', 'access_right', 'address', 'type_users', 'phone', 'email',
            'birthday', 'password', 'avatar')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

authapp/views.py
from django.shortcuts import render, HttpResponseRedirect
from django.utils.decorators import method_decorator
from django.views.generic import DetailView
from authapp.forms import UserLoginForm, UserEditForm, UserUpdateForm, UserRegisterForm
from django.contrib import auth
from django.urls import reverse, reverse_lazy
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView, FormView
from authapp.models import Person
from libapp.models import MainMenu
from edo.utilities import main_menu_generate, weather, groups
from django.contrib.auth.decorators import user_passes_test
from django.contrib import messages


class UserAll(ListView):
    model = Person
    template_name = 'authapp/users/user_list.html'

    @method_decorator(user_passes_test(lambda u: u.is_active))
    def dispatch(self, request, *args, **kwargs):
        return super(UserAll, self).dispatch(request, *args, **kwargs)


class UserProfile(DetailView):
    context = {}
    model = Person
    template_name = 'authapp/users/user_profile.html'
    success_url = reverse_lazy('authapp:profile')
    form_class = UserEditForm

    @method_decorator(user_passes_test(lambda u: u.is_active))
    def dispatch(self, request, *args, **kwargs):
        return super(UserProfile, self).dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(UserProfile, self).get_context_data(**kwargs)
        context['title'] = title = 'редактирование'
        context.update(weather('524901'))
        context.update(groups())
        return context


class UserUpdate(UpdateView):
    model = Person
    template_name = 'authapp/users/user_edit.html'
    success_url = reverse_lazy('authapp:all_user')
    form_class = UserUpdateForm

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, request, *args, **kwargs):
        return super(UserUpdate, self).dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(UserUpdate, self).get_context_data(**kwargs)
        context['title'] = title = 'редактирование'
        return context


class UserRemove(DeleteView):
    model = Person
    template_name = 'authapp/users/user_edit.html'
    success_url = reverse_lazy('authapp:all_user')

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.is_active = False
        self.object.save()
        return HttpResponseRedirect(self.get_success_url())


class UserActive(DeleteView):
    model = Person
    template_name = 'authapp/users/user_edit.html'
    success_url = reverse_lazy('authapp:all_user')

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.is_active = True
        self.object.save()
        return HttpResponseRedirect(self.get_success_url())


def login(request):
    login_form = UserLoginForm(data=request.POST)
    if request.method == 'POST' and login_form.is_valid():
        username = request.POST['username']
        password = request.POST['password']

        user = auth.authenticate(username=username, password=password)
        if user and user.is_active:
            auth.login(request, user)
            return HttpResponseRedirect(reverse('index'))

    context = {'login_form': login_form}
    context.update(main_menu_generate(MainMenu.objects.all()))
    return render(request, 'libapp/index.html', context)


def logout(request):
    auth.logout(request)
    return HttpResponseRedirect(reverse('index'))


def register(request):
    title = 'регистрация'

    if request.method == 'POST':
        register_form = UserRegisterForm(request.POST, request.FILES)

        if register_form.is_valid():
            register_form.save()
            return HttpResponseRedirect(reverse('authapp:login'))
    else:
        register_form = UserRegisterForm()

    context = {'title': title, 'register_form': register_form}
    context.update(main_menu_generate(MainMenu.objects.all()))
    return render(request, 'authapp/register.html', context)


def edit(request):
    title = 'Редактирование профиля'

    if request.method == 'POST':
        edit_form = UserEditForm(request.POST, request.FILES, instance=request.user)
        if edit_form.is_valid():
            edit_form.save()
            return HttpResponseRedirect(reverse('authapp:login'))
    else:
        edit_form = UserEditForm(instance=request.user)

    context = {'title': title, 'edit_form': edit_form}
    context.update(main_menu_generate(MainMenu.objects.all()))
    return render(request, 'authapp/edit.html', context)

authapp/templates/authapp/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, shrink-to-fit=no">
    {% block heads %}{% endblock %}
    <link rel="icon" type="image/x-icon" href="{% static 'assets/img/favicon.ico' %}"/>
    <!-- BEGIN GLOBAL MANDATORY STYLES -->
    <link href="{% static 'assets/css/loader.css' %}" rel="stylesheet" type="text/css"/>
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,600,700' rel='stylesheet' type='text/css'>
    <link href="{% static 'bootstrap/css/bootstrap.min.css' %}" rel="stylesheet" type="text/css"/>
    <link href="{% static 'assets/css/plugins.css' %}" rel="stylesheet" type="text/css"/>
    <!-- END GLOBAL MANDATORY STYLES -->
    {% block css %}{% endblock %}
    <!-- BEGIN PAGE LEVEL PLUGINS/CUSTOM STYLES -->
    <link href="{% static 'plugins/maps/vector/jvector/jquery-jvectormap-2.0.3.css' %}" rel="stylesheet"
          type="text/css"/>
    <link href="{% static 'plugins/charts/chartist/chartist.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'assets/css/default-dashboard/style.css' %}" rel="stylesheet" type="text/css"/>
    <!-- END PAGE LEVEL PLUGINS/CUSTOM STYLES -->
</head>
<body>
<div id="eq-loader">
    <div class="eq-loader-div">
        <div class="eq-loading dual-loader mx-auto mb-5"></div>
    </div>
</div>

<!--  BEGIN NAVBAR  -->
{% include 'authapp/nav.html' %}
<!--  END NAVBAR  -->

<!--  BEGIN MAIN CONTAINER  -->
<div class="main-container" id="container">
    <div class="overlay"></div>
    <div class="ps-overlay"></div>
    <div class="search-overlay"></div>

    <!--  BEGIN MODERN  -->
    {% include 'authapp/side-bar.html' %}
    <!--  END MODERN  -->

    <!--  BEGIN CONTENT PART  -->
    {% block content %}{% endblock %}
    <!--  END CONTENT PART  -->

</div>
<!-- END MAIN CONTAINER -->

<!--  BEGIN FOOTER  -->
{% include 'authapp/footer.html' %}
<!--  END FOOTER  -->

<!--  BEGIN PROFILE SIDEBAR  -->
{% include 'authapp/profile-side.html' %}
<!--  BEGIN PROFILE SIDEBAR  -->

<!-- BEGIN GLOBAL MANDATORY SCRIPTS -->
<script src="{% static 'assets/js/libs/jquery-3.1.1.min.js' %}"></script>
<script src="{% static 'assets/js/loader.js' %}"></script>
<script src="{% static 'bootstrap/js/popper.min.js' %}"></script>
<script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
<script src="{% static 'plugins/scrollbar/jquery.mCustomScrollbar.concat.min.js' %}"></script>
<script src="{% static 'plugins/blockui/jquery.blockUI.min.js' %}"></script>
<script src="{% static 'assets/js/app.js' %}"></script>
<script>
    $(document).ready(function () {
        App.init();
    });
</script>
<script src="{% static 'assets/js/custom.js' %}"></script>
<!-- END GLOBAL MANDATORY SCRIPTS -->

<!-- BEGIN PAGE LEVEL PLUGINS/CUSTOM SCRIPTS -->
<script src="{% static 'plugins/charts/chartist/chartist.js' %}"></script>
<script src="{% static 'plugins/maps/vector/jvector/jquery-jvectormap-2.0.3.min.js' %}"></script>
<script src="{% static 'plugins/maps/vector/jvector/worldmap_script/jquery-jvectormap-world-mill-en.js' %}"></script>
<script src="{% static 'plugins/calendar/pignose/moment.latest.min.js' %}"></script>
<script src="{% static 'plugins/calendar/pignose/pignose.calendar.js' %}"></script>
<script src="{% static 'plugins/progressbar/progressbar.min.js' %}"></script>
<script src="{% static 'assets/js/default-dashboard/default-custom.js' %}"></script>
<!-- BEGIN PAGE LEVEL PLUGINS/CUSTOM SCRIPTS -->
{% block custom_css %}{% endblock %}
{% block footer %}{% endblock %}
</body>
</html>

authapp/templates/authapp/base_clear.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, shrink-to-fit=no">
    {% block heads %}{% endblock %}
    <link rel="icon" type="image/x-icon" href="{% static 'assets/img/favicon.ico' %}"/>
    <!-- BEGIN GLOBAL MANDATORY STYLES -->
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,600,700' rel='stylesheet' type='text/css'>
    <link href="{% static 'bootstrap/css/bootstrap.min.css' %}" rel="stylesheet" type="text/css"/>
    <link href="{% static 'assets/css/plugins.css' %}" rel="stylesheet" type="text/css"/>
    <link href="{% static 'assets/css/users/register-3.css' %}" rel="stylesheet" type="text/css"/>
    <!-- END GLOBAL MANDATORY STYLES -->

</head>
<body class="login">

{% block content %}{% endblock %}

<!-- BEGIN GLOBAL MANDATORY SCRIPTS -->
<script src="{% static 'assets/js/libs/jquery-3.1.1.min.js' %}"></script>
<script src="{% static 'assets/js/loader.js' %}"></script>
<script src="{% static 'bootstrap/js/popper.min.js' %}"></script>
<script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>

<!-- END GLOBAL MANDATORY SCRIPTS -->
</body>
</html>

authapp/templates/authapp/footer.html
{% load staticfiles %}

<!--  BEGIN FOOTER  -->
<footer class="footer-section theme-footer">

    <div class="footer-section-1  sidebar-theme">

    </div>

    <div class="footer-section-2 container-fluid">
        <div class="row">
            <div id="toggle-grid" class="col-xl-7 col-md-6 col-sm-6 col-12 text-sm-left text-center">
                <ul class="list-inline links ml-sm-5">
                    <li class="list-inline-item">
                        <a target="_blank"
                           href="#">Пока незнаю что тут будет</a>
                    </li>
                </ul>
            </div>
            <div class="col-xl-5 col-md-6 col-sm-6 col-12">
                <ul class="list-inline mb-0 d-flex justify-content-sm-end justify-content-center mr-sm-3 ml-sm-0 mx-3">
                    <li class="list-inline-item  mr-3">
                        <p class="bottom-footer">&#xA9; 2021 <a target="_blank" href="#">Equation Admin Theme</a></p>
                    </li>
                    <li class="list-inline-item align-self-center">
                        <div class="scrollTop"><i class="flaticon-up-arrow-fill-1"></i></div>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</footer>
<!--  END FOOTER  -->

authapp/templates/authapp/login.html
{% extends 'libapp/base.html' %}
{% load staticfiles %}


{% block content %}
    <div class="card-header bg-light">
        <h3 class="text-center font-weight-light my-4">Авторизация</h3>
    </div>
    <form class="form-horizontal bg-light" action="{% url 'auth:login' %}" method="post">
        {% csrf_token %}
        {{ login_form.as_table }}
        <br>
        <input class="form-control" type="submit" value="войти">
    </form>
    <hr>
    <button type="button" class="btn btn-block btn-outline-secondary"><a href="{% url 'auth:register' %}">Нужен аккаунт?
        Зарегистрируйся!</a></button>
    <hr>
    <button type="button" class="btn btn-block btn-outline-secondary"><a href="{% url 'libapp:index' %}">Главная
        страница</a></button>
{% endblock %}

authapp/templates/authapp/profile-side.html
{% load staticfiles %}
{% load utilities %}

<!--  BEGIN PROFILE SIDEBAR  -->
{% if user.is_authenticated %}
    <aside class="profile-sidebar text-center">
        <div class="profile-content profile-content-scroll">
            <div class="usr-profile">
                <img src="{{ user.avatar|media_folder_users }}" alt="admin-profile" class="img-fluid">
            </div>
            <p class="user-name mt-4 mb-4">{{ user.first_name }} {{ user.last_name }}</p>
            <div class="">
                <div class="accordion" id="user-stats">
                    <div class="card">
                        <div class="card-header pb-4 mb-4" id="status">
                            <h6 class="mb-0" data-toggle="collapse" data-target="#user-status" aria-expanded="true"
                                aria-controls="user-status"><i class="flaticon-view-3 mr-2"></i> Мой статус <i
                                    class="flaticon-down-arrow ml-2"></i></h6>
                        </div>
                        <div id="user-status" class="collapse show" aria-labelledby="status" data-parent="#user-stats">
                            <div class="card-body text-left">
                                <ul class="list-unstyled pb-4">
                                    <li class="status-online"><a href="javascript:void(0);">Онлайн</a></li>
                                    <li class="status-away"><a href="javascript:void(0);">Отошел</a></li>
                                    <li class="status-no-disturb"><a href="javascript:void(0);">Не беспокоить</a></li>
                                    <li class="status-invisible"><a href="javascript:void(0);">Невидим</a></li>
                                    <li class="status-offline"><a href="javascript:void(0);">Оффлайн</a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="user-links text-left">
                <ul class="list-unstyled">
                    <li><a href="apps_mailbox.html"><i class="flaticon-mail-22"></i> Входящие</a></li>
                    <li><a href="{% url 'authapp:profile' user.pk %}"><i class="flaticon-user-11"></i> Мой профиль</a>
                    </li>
                    <li><a href="{% url 'authapp:logout' %}"><i class="flaticon-power-off"></i> Выход</a></li>
                </ul>
            </div>

        </div>
    </aside>
{% endif %}
<!--  BEGIN PROFILE SIDEBAR  -->

authapp/templates/authapp/register.html
{% extends 'authapp/base_clear.html' %}
{% load staticfiles %}

{% block heads %}
    <title>{{ title }}</title>
{% endblock %}

{% block content %}
    <form class="form-login" action="{% url 'auth:register' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="row">
            <div class="col-md-12 text-center mb-4">
                <img alt="logo" src="{% static 'img/logo2.png' %}" class="theme-logo">
            </div>
            <div class="col-md-12 text-center mb-4">
                {% if register_form.errors %}
                    {% for field in register_form %}
                        {% if field.errors %}
                            <div class="alert alert-arrow-left alert-icon-left alert-light-danger mb-4" role="alert">
                                <i class="flaticon-cancel-12 close" data-dismiss="alert"></i>
                                <i class="flaticon-bell-13"></i>
                                <strong>Ошибка!</strong>{{ field.errors }}
                            </div>
                        {% endif %}
                    {% endfor %}
                {% endif %}
            </div>
            <div class="col-md-12">
                <label for="{{ register_form.username.id_for_label }}" class="">Имя пользователя</label>
                {{ register_form.username }}
                <label for="{{ register_form.first_name.id_for_label }}" class="">Имя</label>
                {{ register_form.first_name }}
                <label for="{{ register_form.last_name.id_for_label }}" class="">Фамилия</label>
                {{ register_form.last_name }}
                <label for="{{ register_form.email.id_for_label }}" class="">EMAIL</label>
                {{ register_form.email }}
                <label for="{{ register_form.password1.id_for_label }}" class="">Пароль</label>
                {{ register_form.password1 }}
                <label for="{{ register_form.password2.id_for_label }}" class="">Повторите пароль</label>
                {{ register_form.password2 }}
                <div class="terms-conditions-chkbox d-flex justify-content-center mb-4">
                    <div class="custom-control custom-checkbox mr-3">
                        <input type="checkbox" class="custom-control-input" id="customCheck1" value="remember-me"
                               onchange="document.getElementById('submit').disabled = !this.checked">
                        <label class="custom-control-label" for="customCheck1"><span class="d-block mt-1">Я согласен со всеми <a
                                href="#">Условиями</a></span></label>
                    </div>
                </div>
                <button type="submit" id="submit" disabled class="btn btn-gradient-dark btn-rounded btn-block">
                    Зарегистрироваться
                </button>
                <div class="forgot-pass text-center mt-4">
                    <a href="{% url 'index' %}">Вернуться на главную</a>
                </div>
            </div>
        </div>
    </form>
{% endblock %}