authapp/urls.py
from django.urls import path
import authapp.views as authapp_views

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp_views.login, name='login'),
    path('logout/', authapp_views.logout, name='logout'),
    path('register/', authapp_views.register, name='register'),
    path('profile/<int:pk>/', authapp_views.UserProfile.as_view(), name='profile'),
    path('all/', authapp_views.UserAll.as_view(), name='all_user'),
    path('active/<int:pk>/', authapp_views.UserActive.as_view(), name='active_user'),
    path('remove/<int:pk>/', authapp_views.UserRemove.as_view(), name='remove_user'),
    path('edit/<int:pk>/', authapp_views.UserUpdate.as_view(), name='edit_user'),
]

blogapp/urls.py
from django.urls import path
import blogapp.views as blogapp_views

app_name = 'blogapp'

urlpatterns = [
    path('', blogapp_views.index, name='index'),
    path('new/', blogapp_views.CreateNewPost.as_view(), name='new_blog'),
    path('list/', blogapp_views.ViewAllPost.as_view(), name='list_blog'),
]

edo/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from libapp import views as libapp_views
from django.conf.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('lib/', include('libapp.urls', namespace='library')),
    path('blog/', include('blogapp.urls', namespace='blog')),
    path('doc/', include('docapp.urls', namespace='docapp')),
    path('', libapp_views.main, name='index'),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blogapp/models.py
from django.db import models
from libapp.models import Category, AccessLevel
from authapp.models import Person


# Create your models here.

class BlogCategory(Category):

    def __init__(self, *args, **kwargs):
        super(BlogCategory, self).__init__(*args, **kwargs)


class Blog(models.Model):
    category = models.ForeignKey(BlogCategory, default=0, on_delete=models.SET_DEFAULT, verbose_name='Категория блога')
    acces_level = models.ForeignKey(AccessLevel, default=0, on_delete=models.SET_DEFAULT, )
    name = models.CharField(verbose_name='Наименование документа', max_length=128)
    cover = models.ImageField(verbose_name='Титульный лист', upload_to='cover', blank=True)
    short_desc = models.CharField(verbose_name='Краткое описание', max_length=60, blank=True)
    description = models.TextField(verbose_name='Описание', blank=True)
    doc_file = models.FileField(verbose_name='Файл документа', upload_to='library', blank=True)
    time_publication = models.DateTimeField(verbose_name='дата публикации статьи', auto_now_add=True)
    author = models.ForeignKey(Person, null=True, on_delete=models.SET_NULL, verbose_name='автор поста', default='')
    published_by = models.BooleanField(verbose_name='Статус публикации', help_text='', default=False)

    def __str__(self):
        return f'({self.category.name}) {self.name} {self.time_publication}'

blogapp/forms.py
from django import forms

from blogapp.models import Blog


class CreateNewPostForm(forms.ModelForm):
    description = forms.CharField(widget=forms.Textarea)

    class Meta:
        model = Blog
        fields = (
            'category', 'acces_level', 'name', 'cover', 'short_desc', 'description', 'doc_file', 'author',
            'published_by')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''
        self.fields['category'].widget.attrs['class'] = 'form-control form-custom mb-4'
        self.fields['acces_level'].widget.attrs['class'] = 'form-control form-custom'
        self.fields['doc_file'].widget.attrs['class'] = 'form-control-file'
        self.fields['cover'].widget.attrs['class'] = 'form-control-file'


class ViewAllPostForm(forms.ModelForm):
    class Meta:
        model = Blog
        fields = (
            'category', 'acces_level', 'name', 'cover', 'short_desc', 'description', 'doc_file', 'author',
            'published_by')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

blogapp/views.py
from django.contrib.auth.decorators import user_passes_test
from django.shortcuts import render
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import DetailView, CreateView, UpdateView, DeleteView, ListView
from django.contrib.auth.models import User

from blogapp.forms import CreateNewPostForm, ViewAllPostForm
from blogapp.models import Blog, BlogCategory
from libapp.models import MainMenu
from authapp.models import Counteragent, Person
from edo.utilities import main_menu_generate, footer_info_generator


# Create your views here.

def index(request):
    blog_category = BlogCategory.objects.all().order_by('pk')
    blog_post = Blog.objects.all().order_by('time_publication')
    context = {
        'title': 'ООО Авиакомпания "БАРКОЛ" - БЛОГ',
        'blog_category': blog_category,
        'blog_post': blog_post,
    }
    context.update(main_menu_generate(MainMenu.objects.all()))
    context.update(footer_info_generator(Counteragent.objects.get(base_counteragent=True)))
    return render(request, 'blogapp/index.html', context)


class ViewAllPost(ListView):
    template_name = 'blogapp/list_view.html'
    model = Blog

    @method_decorator(user_passes_test(lambda u: u.is_active))
    def dispatch(self, request, *args, **kwargs):
        return super(ViewAllPost, self).dispatch(request, *args, **kwargs)


class CreateNewPost(CreateView):
    context = {}
    model = Blog
    user = None
    template_name = 'blogapp/create.html'
    success_url = reverse_lazy('blog:index')
    form_class = CreateNewPostForm

    @method_decorator(user_passes_test(lambda u: u.is_active))
    def dispatch(self, request, *args, **kwargs):
        self.user = request.user
        return super(CreateNewPost, self).dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(CreateNewPost, self).get_context_data(**kwargs)
        context['title'] = title = 'Создание нового поста'
        # context['author'] = self.user
        print(context)
        return context

    def get_form_kwargs(self):
        # pass "user" keyword argument with the current user to your form
        kwargs = super(CreateNewPost, self).get_form_kwargs()
        try:
            _mutable = kwargs['data']._mutable
            kwargs['data']._mutable = True
            kwargs['data']['author'] = self.user.pk
            kwargs['data']._mutable = _mutable
        except Exception:
            print(kwargs)
        return kwargs

blogapp/templates/blogapp/create.html
{% extends 'authapp/base.html' %}
{% load staticfiles %}

{% block heads %}
    <title>{{ title }}</title>
{% endblock %}

{% block css %}
    <!--  BEGIN CUSTOM STYLE FILE  -->
    <link href="{% static 'plugins/jquery-ui/jquery-ui.min.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'assets/css/ecommerce/addedit_product.css' %}" rel="stylesheet" type="text/css">
    <!--  END CUSTOM STYLE FILE  -->
{% endblock %}

{% block content %}
    <!--  BEGIN CONTENT PART  -->
    <div id="content" class="main-content">
        <div class="container">
            <div class="page-header">
                <div class="page-title">
                    <h3>Добавить новую статью</h3>
                </div>
            </div>

            <div class="row">
                <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12 layout-spacing">
                    <div class="statbox widget box box-shadow">

                        <div class="widget-content widget-content-area add-manage-product-2">
                            <div class="row">
                                <div class="col-xl-12 col-md-12">
                                    <div class="card card-default">
                                        <div class="card-heading"><h2 class="card-title"><span>Новый пост</span></h2>
                                        </div>
                                        <div class="card-body">
                                            <div class="card-body">
                                                <form class="form-horizontal" action="{% url 'blogapp:new_blog' %}"
                                                      method="post" enctype="multipart/form-data">
                                                    {% csrf_token %}
                                                    <div class="form-group mb-4">
                                                        <div class="row">
                                                            <label for="{{ form.cover.id_for_label }}" class="col-md-4">Титульный
                                                                лист :</label>
                                                            <div class="col-md-8">
                                                                <div class="mb-3">
                                                                    <div class="custom-file">
                                                                        {{ form.cover }}
                                                                    </div>
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>
                                                    <div class="form-group mb-4">
                                                        <div class="row">
                                                            <label for="{{ form.name.id_for_label }}" class="col-md-4">Заголовок
                                                                :</label>
                                                            <div class="col-md-8">
                                                                {{ form.name }}
                                                            </div>
                                                        </div>
                                                    </div>
                                                    <div class="form-group mb-4">
                                                        <div class="row">
                                                            <label for="{{ form.short_desc.id_for_label }}"
                                                                   class="col-md-4">Краткое описание :</label>
                                                            <div class="col-md-8">
                                                                {{ form.short_desc }}
                                                            </div>
                                                        </div>
                                                    </div>
                                                    <div class="form-group mb-4">
                                                        <div class="row">
                                                            <label for="{{ form.description.id_for_label }}"
                                                                   class="col-md-4">Описание :</label>
                                                            <div class="col-md-8">
                                                                {{ form.description }}
                                                            </div>
                                                        </div>
                                                    </div>
                                                    <div class="form-group mb-4">
                                                        <div class="row">
                                                            <label for="{{ form.category.id_for_label }}"
                                                                   class="col-md-4">Категория блога :</label>
                                                            <div class="col-md-8">
                                                                {{ form.category }}
                                                            </div>
                                                        </div>
                                                    </div>
                                                    <div class="form-group mb-4">
                                                        <div class="row">
                                                            <label for="{{ form.acces_level.id_for_label }}"
                                                                   class="col-md-4">Уровень доступа :</label>
                                                            <div class="col-md-8">
                                                                {{ form.acces_level }}
                                                            </div>
                                                        </div>
                                                    </div>
                                                    <div class="form-group mb-4">
                                                        <div class="row">
                                                            <label for="{{ form.published_by.id_for_label }}"
                                                                   class="col-md-4">Опубликовать :</label>
                                                            <div class="col-md-8">
                                                                {{ form.published_by }}
                                                            </div>
                                                        </div>
                                                    </div>
                                                    <div class="form-group mb-4">
                                                        <div class="row">
                                                            <label for="{{ form.doc_file.id_for_label }}"
                                                                   class="col-md-4">Документ :</label>
                                                            <div class="col-md-8">
                                                                <div class="mb-3">
                                                                    <div class="custom-file">
                                                                        {{ form.doc_file }}
                                                                    </div>
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>
                                                    <div class="form-group mb-4 invisible">
                                                        <div class="row">
                                                            <label for="{{ form.author.id_for_label }}"
                                                                   class="col-md-4">Заголовок :</label>
                                                            <div class="col-md-8">
                                                                {{ form.author }}
                                                            </div>
                                                        </div>
                                                    </div>
                                                    <div class="align-center">
                                                        <input value="Insert Product" class="btn" type="submit">
                                                    </div>
                                                </form>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    </div>
    <!--  END CONTENT PART  -->
{% endblock %}

{% block custom_css %}
    <!--  BEGIN CUSTOM SCRIPT FILES  -->
    <script src="{% static 'assets/js/ecommerce/autocomplete-addedit_product.js' %}"></script>
    <!--  END CUSTOM SCRIPT FILES  -->
{% endblock %}

blogapp/templates/blogapp/index.html
{% extends 'libapp/base.html' %}
{% load staticfiles %}
{% load utilities %}

{% block heads %}
    <title>{{ title }}</title>
{% endblock %}

{% block content %}
    <section class="rq-page-background rq-blog-page-bg">
        <div class="banner_shadow">
            <h1>BLOG</h1>
        </div>
    </section>

    <section class="rq-blog-post-section" id="blog-post">
        <div class="container">
            <div class="row">
                <div class="col-md-8 col-sm-7 rq-blog-post-wrapper">
                    {% for item in blog_post %}
                        {% if item.published_by %}
                            <!-- BLOG ITEMS -->
                            <div class="rq-blog-items rq-image-post">
                                <div class="rq-blog-img-wrapper">
                                    <img src="{{ item.cover|media_folder_blog_cover }}" alt="Blog Image">
                                    <div class="rq-blog-cat-icon">
                                        <i class="ion-ios-camera-outline"></i>
                                    </div>
                                </div>

                                <div class="rq-blog-item-details">
                                    <h3>
                                        <a href="#">{{ item.name }}</a>
                                    </h3>
                                    <h5>{{ item.short_desc }}</h5>
                                    <p>{{ item.description }}</p>
                                    <div>
                                        <ol class="breadcrumb">
                                            <li>
                                                <time datetime="{{ item.time_publication }}">{{ item.time_publication }}</time>
                                            </li>
                                            <li class="active"><a href="{% url 'authapp:edit_user' item.author.pk %}">{{ item.author }}</a></li>
                                            <li><a href="">COMMENT<span> 3</span></a></li>
                                        </ol>
                                    </div>
                                </div>
                            </div>
                            <!-- BLOG ITEMS END -->
                        {% endif %}
                    {% endfor %}
                </div>

                <div class="col-md-4 col-sm-5 rq-sidebar">
                    <div class="rq-sidebar-wrapper">
                        <!-- SIDEBAR WIDGET -->
                        <div class="rq-sidebar-widget rq-recent-post-widget">
                            <h3 class="rq-sidebar-title">Последние посты</h3>

                            <div class="rq-recent-post-wrapper">
                                {% for item in blog_post %}
                                    <!-- POST ITEM -->
                                    <div class="rq-recent-post-item">
                                        <div class="rq-recent-post-img-wrapper">
                                            <img src="{% static 'img/placeholder-70.jpg' %}" alt="Последние пост">
                                        </div>

                                        <div class="rq-recent-post-details">
                                            <h3><a href="#">{{ item.name }}</a></h3>
                                            <span class="rq-post-date">{{ item.time_publication }}</span>
                                        </div>
                                    </div>
                                    <!-- END -->
                                {% endfor %}
                            </div>
                        </div>
                        <!-- END -->

                        <!-- SIDEBAR WIDGET -->
                        <div class="rq-sidebar-widget rq-category-widget">
                            <h3 class="rq-sidebar-title">Категории блога</h3>
                            <ul>
                                {% for item in blog_category %}
                                    <li><a href="#">{{ item.name }}</a></li>
                                {% endfor %}
                            </ul>
                        </div>
                        <!-- END -->
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

blogapp/templates/blogapp/list_view.html
{% extends 'authapp/base.html' %}
{% load staticfiles %}
{% load utilities %}

{% block heads %}
    <title>{{ title }}</title>
{% endblock %}

{% block css %}
    <!-- BEGIN PAGE LEVEL CUSTOM STYLES -->
    <link rel="stylesheet" type="text/css" href="{% static 'plugins/table/datatable/datatables.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'plugins/table/datatable/custom_dt_customer.css' %}">
    <!-- END PAGE LEVEL CUSTOM STYLES -->
{% endblock %}

{% block content %}

    <!--  BEGIN CONTENT PART  -->
    <div id="content" class="main-content">
        <div class="container">
            <div class="page-header">
                <div class="page-title">
                    <h3>Custom DataTables</h3>
                </div>
            </div>

            <div class="row layout-spacing">
                <div class="col-lg-12">
                    <div class="statbox widget box box-shadow">
                        <div class="widget-header">
                            <div class="row">
                                <div class="col-xl-12 col-md-12 col-sm-12 col-12">
                                    <h4>Все посты</h4>
                                </div>
                            </div>
                        </div>
                        <div class="widget-content widget-content-area">
                            <div class="table-responsive mb-4 style-1">
                                <table id="customer-info-detail-1" class="table style-1  table-bordered table-hover">
                                    <thead>
                                    <tr>
                                        <th class="checkbox-column"> Номер</th>
                                        <th>Наименование</th>
                                        <th>Титульная картинка</th>
                                        <th>Краткое описание</th>
                                        <th>Описание</th>
                                        <th>Время публикации</th>
                                        <th>Автор</th>
                                        <th class="">Статус публикации</th>
                                        <th class="text-center">Действия</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    {% for elem in object_list %}
                                        <tr>
                                            <td class="checkbox-column">{{ elem.pk }}</td>
                                            <td class="customer-name-1">{{ elem.name }}</td>
                                            <td class="">
                                                <a class="product-list-img" href="javascript: void(0);">
                                                    <img src="{{ elem.cover|media_folder_blog_cover }}" alt="product">
                                                </a>
                                            </td>
                                            <td>{{ elem.short_desc }}</td>
                                            <td>{{ elem.description }}</td>
                                            <td>{{ elem.time_publication }}</td>
                                            <td>{{ elem.author }}</td>
                                            <td>
                                                <div class="d-flex">
                                                    <div class=" align-self-center {% if elem.published_by %}d-m-success{% else %}d-m-danger{% endif %}  mr-1 data-marker"></div>
                                                    <span class="{% if elem.published_by %}label label-success{% else %}label label-danger{% endif %}">{% if elem.published_by %}
                                                        Опубликован{% else %}Скрыт{% endif %}</span>
                                                </div>
                                            </td>
                                            <td class="text-center">
                                                <div class="dropdown custom-dropdown">
                                                    <a class="dropdown-toggle" href="#" role="button"
                                                       id="dropdownMenuLink1"
                                                       data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                                                        <i class="flaticon-dot-three"></i>
                                                    </a>

                                                    <div class="dropdown-menu" aria-labelledby="dropdownMenuLink1">
                                                        <a class="dropdown-item" href="javascript:void(0);">Просмотр</a>
                                                        <a class="dropdown-item" href="javascript:void(0);">Редактирование</a>
                                                        <a class="dropdown-item"
                                                           href="javascript:void(0);">Комментарии</a>
                                                        <a class="dropdown-item" href="javascript:void(0);">Удаление</a>
                                                    </div>
                                                </div>
                                            </td>
                                        </tr>
                                    {% endfor %}

                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
    <!--  END CONTENT PART  -->

{% endblock %}

{% block custom_css %}
    <!-- BEGIN PAGE LEVEL SCRIPTS -->
    <script src="{% static 'plugins/table/datatable/datatables.js' %}"></script>
    <script>
        // var e;
        c1 = $('#customer-info-detail-1').DataTable({
            "lengthMenu": [5, 10, 20, 50, 100],
            headerCallback: function (e, a, t, n, s) {
                e.getElementsByTagName("th")[0].innerHTML = '<label class="new-control new-checkbox checkbox-outline-primary m-auto">\n<input type="checkbox" class="new-control-input chk-parent select-customers-info" id="customer-all-info">\n<span class="new-control-indicator"></span><span style="visibility:hidden">c</span>\n</label>'
            },
            columnDefs: [{
                targets: 0, width: "30px", className: "", orderable: !1, render: function (e, a, t, n) {
                    return '<label class="new-control new-checkbox checkbox-outline-primary  m-auto">\n<input type="checkbox" class="new-control-input child-chk select-customers-info" id="customer-all-info">\n<span class="new-control-indicator"></span><span style="visibility:hidden">c</span>\n</label>'
                }
            }],
            "language": {
                "paginate": {
                    "previous": "<i class='flaticon-arrow-left-1'></i>",
                    "next": "<i class='flaticon-arrow-right'></i>"
                },
                "info": "Показана страница _PAGE_ из _PAGES_"
            }
        });

        multiCheck(c1);

        c2 = $('#customer-info-detail-2').DataTable({
            "lengthMenu": [5, 10, 20, 50, 100],
            headerCallback: function (e, a, t, n, s) {
                e.getElementsByTagName("th")[0].innerHTML = '<label class="new-control new-checkbox checkbox-outline-primary m-auto">\n<input type="checkbox" class="new-control-input chk-parent select-customers-info" id="customer-all-info">\n<span class="new-control-indicator"></span><span style="visibility:hidden">c</span>\n</label>'
            },
            columnDefs: [{
                targets: 0, width: "30px", className: "", orderable: !1, render: function (e, a, t, n) {
                    return '<label class="new-control new-checkbox checkbox-outline-primary  m-auto">\n<input type="checkbox" class="new-control-input child-chk select-customers-info" id="customer-all-info">\n<span class="new-control-indicator"></span><span style="visibility:hidden">c</span>\n</label>'
                }
            }],
            "language": {
                "paginate": {
                    "previous": "<i class='flaticon-arrow-left-1'></i>",
                    "next": "<i class='flaticon-arrow-right'></i>"
                },
                "info": "Показана страница _PAGE_ из _PAGES_"
            }
        });

        multiCheck(c2);

        c3 = $('#customer-info-detail-3').DataTable({
            "lengthMenu": [5, 10, 20, 50, 100],
            "language": {
                "paginate": {
                    "previous": "<i class='flaticon-arrow-left-1'></i>",
                    "next": "<i class='flaticon-arrow-right'></i>"
                },
                "info": "Показана страница _PAGE_ из _PAGES_"
            }
        });

        multiCheck(c3);
    </script>
    <!-- END PAGE LEVEL SCRIPTS -->
{% endblock %}